const express=require('express');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const app=express();
const PORT=Number(process.env.PORT||3000);
const ROOT=__dirname;
const catalog=JSON.parse(fs.readFileSync(path.join(ROOT,'data/catalog.json'),'utf8'));
const productMap=new Map(catalog.map(p=>[Number(p.id),p]));
const orders=new Map();
const otpStore=new Map();
const rate=new Map();
const owners=(process.env.HEEBA_OWNER_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);
const developers=(process.env.HEEBA_DEVELOPER_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);
const OTP_TTL=5*60*1000;
function normalize(p){p=String(p||'').replace(/\s+/g,'');if(p.startsWith('05'))p='+966'+p.slice(1);if(p.startsWith('966'))p='+'+p;return p}
function jsonError(res,status,code){return res.status(status).json({error:code})}
function secureHeaders(req,res,next){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' https://cdn.moyasar.com; style-src 'self' 'unsafe-inline' https://cdn.moyasar.com https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.moyasar.com https://api.sendgrid.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");next()}
function limiter(key,limit=30,windowMs=60000){const now=Date.now();const x=rate.get(key);if(!x||now-x.start>windowMs){rate.set(key,{start:now,count:1});return true}x.count++;return x.count<=limit}
function sameOrigin(req){const o=req.get('origin');return !o||o===`${req.protocol}://${req.get('host')}`}
app.disable('x-powered-by');app.use(secureHeaders);app.use(express.json({limit:'32kb'}));
app.use('/api', (req,res,next)=>{if(req.method==='POST'&&!sameOrigin(req))return jsonError(res,403,'BAD_ORIGIN');const key=`${req.ip}:${req.path}`;if(!limiter(key,60,60000))return jsonError(res,429,'RATE_LIMIT');next()});
app.use(express.static(ROOT,{extensions:['html']}));
app.get('/api/payment/config',(req,res)=>{res.json({enabled:Boolean(process.env.MOYASAR_PUBLISHABLE_KEY),publishableKey:process.env.MOYASAR_PUBLISHABLE_KEY||null,methods:['card','apple','google'],currency:'SAR',provider:'moyasar'})});
function validateCart(items){if(!Array.isArray(items)||items.length<1||items.length>30)throw new Error('CART_INVALID');let total=0;const clean=[];for(const raw of items){const id=Number(raw?.id),qty=Number(raw?.qty);const p=productMap.get(id);if(!p||!Number.isInteger(qty)||qty<1||qty>10||qty>p.stock)throw new Error('CART_INVALID');const selections=raw.selections&&typeof raw.selections==='object'?raw.selections:{};for(let i=0;i<(p.options||[]).length;i++){const g=p.options[i];const v=selections[String(i)] ?? selections[i];if(g.required&&!g.values.includes(v))throw new Error('CART_INVALID');if(v!==undefined&&!g.values.includes(v))throw new Error('CART_INVALID')}total+=p.price*qty;clean.push({id:p.id,name:p.name,price:p.price,qty,selections});}if(!Number.isSafeInteger(Math.round(total*100))||total<1)throw new Error('CART_INVALID');return {total,currency:'SAR',items:clean}}
app.post('/api/checkout/prepare',(req,res)=>{try{const method=String(req.body?.paymentMethod||'');if(!['card','apple','google'].includes(method))return jsonError(res,400,'PAYMENT_METHOD_INVALID');const customer=req.body?.customer||{};const name=String(customer.name||'').trim(),phone=normalize(customer.phone),address=String(customer.address||'').trim();if(name.length<2||name.length>100||!/^(\+9665\d{8})$/.test(phone)||address.length<5||address.length>240)return jsonError(res,400,'CUSTOMER_INVALID');const cart=validateCart(req.body.items);const orderId=`HB-${crypto.randomUUID()}`;const record={orderId,createdAt:new Date().toISOString(),customer:{name,phone,address},paymentMethod:method,total:cart.total,currency:'SAR',items:cart.items,status:'awaiting_payment'};orders.set(orderId,record);res.json({orderId,amountHalalas:Math.round(cart.total*100),currency:'SAR',items:cart.items,paymentMethod:method})}catch(e){jsonError(res,400,e.message==='CART_INVALID'?'CART_INVALID':'CHECKOUT_INVALID')}});
async function moyasarRetrieve(id){const key=process.env.MOYASAR_SECRET_KEY;if(!key)throw new Error('MOYASAR_NOT_CONFIGURED');const auth=Buffer.from(`${key}:`).toString('base64');const r=await fetch(`https://api.moyasar.com/v1/payments/${encodeURIComponent(id)}`,{headers:{Authorization:`Basic ${auth}`,Accept:'application/json'}});if(!r.ok)throw new Error('PAYMENT_LOOKUP_FAILED');return r.json()}
app.post('/api/payment/verify',(req,res)=>{const {orderId,paymentId}=req.body||{};if(typeof orderId!=='string'||typeof paymentId!=='string'||orderId.length>80||paymentId.length>120)return jsonError(res,400,'INVALID_INPUT');const order=orders.get(orderId);if(!order)return jsonError(res,404,'ORDER_NOT_FOUND');moyasarRetrieve(paymentId).then(p=>{const valid=p.status==='paid'&&p.currency==='SAR'&&Number(p.amount)===Math.round(order.total*100)&&(!p.metadata||!p.metadata.order_id||p.metadata.order_id===orderId);if(!valid)return jsonError(res,400,'PAYMENT_NOT_VERIFIED');order.paymentId=p.id;order.status='paid';orders.set(orderId,order);res.json({ok:true,orderId,status:'paid'})}).catch(()=>jsonError(res,502,'PAYMENT_PROVIDER_ERROR'))});
app.post('/api/webhooks/moyasar',(req,res)=>{const secret=process.env.MOYASAR_WEBHOOK_SECRET||'';if(!secret)return jsonError(res,503,'WEBHOOK_NOT_CONFIGURED');const got=String(req.body?.secret_token||'');const a=Buffer.from(got),b=Buffer.from(secret);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return jsonError(res,401,'WEBHOOK_UNAUTHORIZED');const data=req.body?.data||{};const paymentId=data.id;if(req.body?.type==='payment_paid'){for(const o of orders.values()){if(o.paymentId===paymentId||req.body?.data?.metadata?.order_id===o.orderId){o.paymentId=paymentId;o.status='paid';orders.set(o.orderId,o);break}}}res.status(200).json({ok:true})});
async function sendEmailOtp(email,code){
  const apiKey=process.env.SENDGRID_API_KEY;
  const from=process.env.SENDGRID_FROM_EMAIL||'noreply@heeba.store';
  if(!apiKey)throw new Error('SENDGRID_NOT_CONFIGURED');
  const html=`<div style="direction:rtl;text-align:center;font-family:Arial,sans-serif;padding:30px;background:#0a0a0b;color:#f5f3f1;border-radius:16px"><h2 style="color:#d74d54">هيبة · ثوب سبعة</h2><p style="color:#918f92;font-size:14px">رمز التحقق الخاص بك</p><div style="font-size:42px;font-weight:900;letter-spacing:8px;color:#fff;margin:20px 0;padding:16px;background:#151519;border-radius:12px;border:1px solid #2a2a30">${code}</div><p style="color:#77757a;font-size:12px">صالح لمدة 5 دقائق فقط</p><p style="color:#77757a;font-size:10px">لا تشاركه مع أي شخص</p></div>`;
  const r=await fetch('https://api.sendgrid.com/v3/mail/send',{method:'POST',headers:{'Authorization':'Bearer '+apiKey,'Content-Type':'application/json'},body:JSON.stringify({personalizations:[{to:[{email}],subject:'كود التحقق — هيبة'}],from:{email:from,name:'Heeba Store'},content:[{type:'text/html',value:html}]})});
  if(!r.ok){const err=await r.text().catch(()=>'');throw new Error('EMAIL_SEND_FAILED: '+r.status+' '+err.substring(0,200))}
}
app.post('/api/auth/request-otp',async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return jsonError(res,400,'INVALID_EMAIL');const key=`otp:${req.ip}:${email}`;if(!limiter(key,5,10*60*1000))return jsonError(res,429,'OTP_RATE_LIMIT');const code=String(crypto.randomInt(0,1000000)).padStart(6,'0');otpStore.set(email,{hash:crypto.createHmac('sha256',process.env.OTP_PEPPER||'heeba-dev-pepper').update(code).digest('hex'),expires:Date.now()+OTP_TTL,attempts:0});try{await sendEmailOtp(email,code);res.json({ok:true})}catch(e){otpStore.delete(email);jsonError(res,503,'EMAIL_NOT_CONFIGURED: '+e.message)}});
app.post('/api/auth/verify-otp',(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),code=String(req.body?.otp||'');const x=otpStore.get(email);if(!x||x.expires<Date.now()||x.attempts>=5)return jsonError(res,401,'OTP_INVALID');x.attempts++;const hash=crypto.createHmac('sha256',process.env.OTP_PEPPER||'heeba-dev-pepper').update(code).digest('hex');const ok=crypto.timingSafeEqual(Buffer.from(hash),Buffer.from(x.hash));if(!ok)return jsonError(res,401,'OTP_INVALID');otpStore.delete(email);const role=owners.includes(email)?'owner':developers.includes(email)?'developer':'customer';res.json({ok:true,name:role==='owner'?'مالك هيبة':role==='developer'?'مطور هيبة':'عميل هيبة',role,token:crypto.randomBytes(32).toString('hex')})});
app.get('/api/payment/status',(req,res)=>res.json({provider:'moyasar',configured:Boolean(process.env.MOYASAR_PUBLISHABLE_KEY&&process.env.MOYASAR_SECRET_KEY),webhookConfigured:Boolean(process.env.MOYASAR_WEBHOOK_SECRET),allowedMethods:['mada','visa','applepay','googlepay']}));
app.listen(PORT,()=>console.log(`HEEBA secure server on http://localhost:${PORT}`));
